INSERT INTO USERS (UUID, USER_ID, USER_NAME, PASSWORD, ROLE)
VALUES (UUID(), 'admin', '관리자', 'admin','ADMIN');

INSERT INTO USERS (UUID, USER_ID, USER_NAME, PASSWORD, ROLE)
VALUES (UUID(), 'sks93', '심규성', 'sks93','USER');