INSERT INTO USERS (ID, USER_ID, USERNAME, PASSWORD, ROLE)
VALUES (UUID(), 'admin', '관리자', '$2a$10$z4v2R4./Wj9/l9TQJ/k3xORHD.YPrr4YygaZn0OTxEuuV50GaNMwu','ROLE_ADMIN');

INSERT INTO USERS (ID, USER_ID, USERNAME, PASSWORD, ROLE)
VALUES (UUID(), 'sks93', '심규성', '$2a$10$wWBxBs7Z6wtKdEsJpc8OguIEkn5WcIYuj9rY3h0sX9cjE8ZTAYhBC','ROLE_USER');
