DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
	UUID		UUID			PRIMARY KEY,
	USER_ID		VARCHAR(255)	NOT NULL,
	USER_NAME	VARCHAR(255)	NOT NULL,
	PASSWORD	VARCHAR(255)	NOT NULL,
	ROLE		VARCHAR(100)	NOT	NULL
);