server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/KC_DB;MODE=PostgreSQL;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        "[format_sql]": true
        "[show_sql]": true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: 
      - classpath:db/schema.sql
      data-locations: 
      - classpath:db/data.sql
